-- 1. 데이터베이스 생성 및 UTF-8(utf8mb4) 설정
CREATE DATABASE IF NOT EXISTS `post`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE `post`;

-- 2. 외래키 체크 해제 후 기존 테이블 깔끔하게 삭제 (초기화)
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `POST_UPLOAD`;
DROP TABLE IF EXISTS `IMAGE_UPLOAD`;
DROP TABLE IF EXISTS `POST`;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 3. 게시글 테이블 (POST) - 회원 없이 단독 운영 & 한글 깨짐 방지
-- ============================================================
CREATE TABLE `POST` (
    `POST_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '게시글 PK',
    `WRITER` VARCHAR(50) NULL DEFAULT '익명' COMMENT '작성자 이름',
    `TITLE` VARCHAR(200) NOT NULL COMMENT '게시글 제목',
    `CONTENT` TEXT NOT NULL COMMENT '게시글 내용',
    `IS_BLOCK` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '차단 여부',
    `PLACE` VARCHAR(100) NULL COMMENT '여행 장소',
    `TRANSPORT_COST` INT DEFAULT 0 COMMENT '교통비',
    `FOOD_COST` INT DEFAULT 0 COMMENT '식비',
    `OTHER_COST` INT DEFAULT 0 COMMENT '기타 비용',
    `VIEW_COUNT` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '조회 수',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성 일시',
    `UPDATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (`POST_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='게시글';

-- ============================================================
-- 4. 파일/이미지 업로드 테이블 (IMAGE_UPLOAD)
-- ============================================================
CREATE TABLE `IMAGE_UPLOAD` (
    `UPLOAD_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '파일 PK',
    `ORIGIN_NAME` VARCHAR(255) NOT NULL COMMENT '원본 파일명',
    `UPLOAD_PATH` VARCHAR(500) NOT NULL COMMENT '서버 저장 경로',
    `IMAGE_ORDER` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '이미지 순서',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '업로드 일시',
    PRIMARY KEY (`UPLOAD_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_unicode_ci COMMENT='업로드 파일 정보';

-- ============================================================
-- 5. 게시글-이미지 매핑 테이블 (POST_UPLOAD)
-- ============================================================
CREATE TABLE `POST_UPLOAD` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '매핑 PK',
    `POST_ID` BIGINT NOT NULL COMMENT '게시글 PK',
    `UPLOAD_ID` BIGINT NOT NULL COMMENT '파일 PK',
    PRIMARY KEY (`ID`),
    CONSTRAINT `UK_POST_UPLOAD_POST_UPLOAD` UNIQUE (`POST_ID`, `UPLOAD_ID`),
    CONSTRAINT `FK_POST_UPLOAD_POST` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_POST_UPLOAD_UPLOAD` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `IMAGE_UPLOAD` (`UPLOAD_ID`) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_unicode_ci COMMENT='게시글-파일 매핑';

COMMIT;